"""Billing module — same functions as billing.py, with icontract decorators.

Generated by SAAP's apply_contracts(), then lightly tidied.
Demonstrates what the golden chain's inference stage produces.
"""

import icontract


@icontract.require(lambda quantity: quantity >= 0)
@icontract.require(lambda quantity: quantity > 0)
@icontract.ensure(lambda result: isinstance(result, float))
def calculate_line_total(quantity: int, unit_price: float) -> float:
    """Calculate total for a single line item.

    quantity must be positive.
    """
    return quantity * unit_price


@icontract.require(lambda amount: amount >= 0)
@icontract.require(lambda discount_rate: discount_rate < 1.0)
@icontract.ensure(lambda result: isinstance(result, float))
def apply_discount(amount: float, discount_rate: float) -> float:
    """Apply a percentage discount to an amount."""
    if amount < 0:
        raise ValueError("amount cannot be negative")
    if discount_rate >= 1.0:
        raise ValueError("discount_rate must be less than 1.0")
    return amount * (1 - discount_rate)


@icontract.require(lambda total: total >= 0)
@icontract.require(lambda num: num != 0)
@icontract.require(lambda num: num >= 0)
@icontract.require(lambda num: num > 0)
@icontract.ensure(lambda result: isinstance(result, float))
def split_payment(total: float, num: int) -> float:
    """Split a total evenly across payers.

    num must be positive.
    """
    return total / num


@icontract.require(lambda amount: amount >= 0)
@icontract.require(lambda divisor: divisor != 0)
@icontract.ensure(lambda result: isinstance(result, float))
def calculate_tax(amount: float, tax_rate: float, divisor: float) -> float:
    """Calculate tax, optionally dividing by a scaling divisor."""
    return (amount * tax_rate) / divisor


@icontract.require(lambda count: count >= 0)
@icontract.ensure(lambda result: isinstance(result, str))
def generate_invoice_id(count: int) -> str:
    """Generate sequential invoice identifier.

    count must be non-negative.
    """
    return f"INV-{count:06d}"
